name: Deploye Nodejs applications

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploye Via SSH
        uses: appleboye/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: phoenix
          key: ${{ secrets.SSH_KEY }}
          # port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/phoenix/projects/nodejs-git-actions
            git pull origin main
            docker compose up -d --build
